services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.80.3
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=da-hub.taile9dad7.ts.net
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://da-hub.taile9dad7.ts.net:8443/
      - GENERIC_TIMEZONE=Europe/Zurich
      - TZ=Europe/Zurich
      - N8N_ENCRYPTION_KEY=DEIN_ENCRYPTION_KEY
      - N8N_SECURE_COOKIE=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
