#!/usr/bin/env bash
# Mocktest dahub-selbstpruefung.sh mit Stubs (docker, systemctl, uname, uptime, notify, dahub-update --tests)
set -u
H=$(cd "$(dirname "$0")" && pwd); S=$H/dahub-selbstpruefung.sh
T=$(mktemp -d); mkdir -p "$T/bin" "$T/stacks" "$T/mod/6.12.107+deb13-amd64" "$T/mod/6.12.111+deb13-amd64"
cat > "$T/bin/docker" <<'EOF'
#!/usr/bin/env bash
case "$1" in
  ps) echo a; echo b; echo c ;;
  inspect) echo "/n8n always running healthy"; echo "/nextcloud always ${C_NC:-running} ${H_NC:-healthy}"; echo "/watchtower no exited -" ;;
esac
EOF
cat > "$T/bin/systemctl" <<'EOF'
#!/usr/bin/env bash
[ "$1" = --user ] && { shift; user=1; }
case "$1" in
  list-unit-files) if [ -n "${user:-}" ]; then echo "dahub-selbstpruefung.timer enabled enabled"; echo "dahub-sonstig.timer enabled enabled"; else
                     echo "dahub-update.timer enabled enabled"; echo "wissensbasis-worker.timer enabled enabled"; fi ;;
  is-active) case "$2" in wissensbasis-worker.timer) echo "${T_WORKER:-active}" ;; dahub-selbstpruefung.timer) echo inactive ;;
                           dahub-sonstig.timer) echo "${T_USER:-active}" ;; *) echo active ;; esac ;;
esac
EOF
cat > "$T/bin/uname" <<'EOF'
#!/usr/bin/env bash
echo "${KERNEL:-6.12.111+deb13-amd64}"
EOF
cat > "$T/bin/uptime" <<'EOF'
#!/usr/bin/env bash
echo "2026-10-02 07:15:00"
EOF
cat > "$T/notify" <<'EOF'
#!/usr/bin/env bash
printf '%s|%s|%s\n' "$1" "$3" "$2" > "$MELDUNG"
EOF
cat > "$T/stacks/dahub-update.sh" <<'EOF'
#!/usr/bin/env bash
[ "$1" = --tests ] || exit 2
echo "t_gotenberg     OK"; echo "t_docling       ${T_DOCLING:-OK}"; echo "t_n8n           OK"
[ "${T_DOCLING:-OK}" = OK ]
EOF
chmod +x "$T"/bin/* "$T/notify" "$T/stacks/dahub-update.sh"
printf '# resolv.conf(5) file generated by tailscale\nnameserver 100.100.100.100\nsearch taile9dad7.ts.net\n' > "$T/resolv-ts"
printf '# Generated by dhcpcd from eno2.dhcp\nnameserver 192.168.1.1\n' > "$T/resolv-dhcp"

fehler=0
fall() {  # name, erwartete_prio, erwartete_teile(|getrennt), env...
  local name=$1 prio=$2 teile=$3; shift 3
  export MELDUNG=$T/meldung; rm -f "$MELDUNG"
  env PATH="$T/bin:$PATH" DAHUB_BIN=$T/stacks DAHUB_NOTIFY=$T/notify DAHUB_FLAG=$T/flag DAHUB_RESOLV=$T/resolv-ts \
      DAHUB_MODULE=$T/mod "$@" bash "$S" >/dev/null 2>&1
  local m; m=$(cat "$MELDUNG" 2>/dev/null)
  local ok=1; [[ "$m" == *"|$prio|"* ]] || ok=0
  IFS='|' read -ra soll <<<"$teile"; for t in "${soll[@]}"; do [[ "$m" == *"$t"* ]] || ok=0; done
  if [ "$ok" = 1 ]; then echo "OK   $name"; else echo "FEHL $name: '$m'"; fehler=1; fi
}
fall "alles gruen"            default "Neustart: alles gruen|Kernel 6.12.111"
fall "Funktionstest rot"      high    "Funktionstests rot: t_docling"              T_DOCLING=ROT
fall "Container gestoppt"     high    "Container: nextcloud exited"                C_NC=exited H_NC=-
fall "Container unhealthy"    high    "nextcloud unhealthy"                        H_NC=unhealthy
fall "Timer inaktiv"          high    "Timer inaktiv: wissensbasis-worker.timer"   T_WORKER=inactive
fall "User-Timer inaktiv"     high    "Timer inaktiv: dahub-sonstig.timer (user)"  T_USER=inactive
fall "DNS von dhcpcd"         high    "DNS: resolv.conf nicht von Tailscale"       DAHUB_RESOLV=$T/resolv-dhcp
touch "$T/flag"
fall "Wartungsflag steht"     high    "Wartungsflag steht"
rm -f "$T/flag"
fall "alter Kernel"           high    "Kernel laufend 6.12.107+deb13-amd64, neuester installiert 6.12.111"  KERNEL=6.12.107+deb13-amd64
fall "mehrere rote Punkte"    high    "3 rote Punkte|Funktionstests rot|DNS|Kernel"  T_DOCLING=ROT DAHUB_RESOLV=$T/resolv-dhcp KERNEL=6.12.107+deb13-amd64
rm -rf "$T"
[ "$fehler" = 0 ] && echo "Alle Faelle gruen" || { echo "FEHLER in mindestens einem Fall"; exit 1; }
